language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements_websockets.txt
  - pip install coveralls

script:
  - export PYTHONWARNINGS=all
  - python setup.py test
  - coverage run --source="./utils" --omit="*__init__.py" setup.py test

after_success:
  coveralls
