image:
- Visual Studio 2013
- Visual Studio 2015
- Visual Studio 2017

environment:
  matrix:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  # We need wheel installed to install wheel packages
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip wheel -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip wheel -r requirements_websockets.txt"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py test"
